// <auto-generated />
namespace ContactCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class v1_addingCustOrderTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1_addingCustOrderTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202010121244033_v1_addingCustOrderTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
