CREATE TABLE `Book` (
	`ID` INT NOT NULL,
	`Name` VARCHAR(50) NOT NULL,
	`AUTHOR` VARCHAR(50) NULL DEFAULT NULL,
	`DUEDATE` DATE NOT NULL,
	PRIMARY KEY (`ID`)
);


CREATE TABLE `Library` (
	`ID` INT NOT NULL,
	`Name` VARCHAR(50) NOT NULL,
	`LOCATION` VARCHAR(50) NOT NULL,
	`BOOKID` INT NOT NULL ,
	CONSTRAINT `FK__book` FOREIGN KEY (`BOOKID`) REFERENCES `book` (`ID`)
);

INSERT INTO book VALUE(1,'Glimpses of World History',' Jawaharlal Nehru','2020-7-15');
INSERT INTO book VALUE(2,'An Autobiography','Jawaharlal Nehru','2020-6-15');
INSERT INTO book VALUE(3,'Gita Govinda','Jayadev','2020-7-01');
INSERT INTO book VALUE(4,'Prison Diary','jayaprakash Narayan','2020-7-5');
INSERT INTO book VALUE(5,'Harry Potter','J. K. Rowling ','2020-9-20');

INSERT INTO library VALUE (101,'CENTRAL LIBRARY','MUMBAI',1);
INSERT INTO library VALUE (101,'CENTRAL LIBRARY','MUMBAI',2);
INSERT INTO library VALUE (101,'CENTRAL LIBRARY','MUMBAI',3);
INSERT INTO library VALUE (101,'CENTRAL LIBRARY','MUMBAI',4);
INSERT INTO library VALUE (101,'CENTRAL LIBRARY','MUMBAI',5);
INSERT INTO library VALUE (102,'CENTRAL LIBRARY','PUNE',2);
INSERT INTO library VALUE (102,'CENTRAL LIBRARY','PUNE',3);
INSERT INTO library VALUE (102,'CENTRAL LIBRARY','PUNE',4);


SELECT * FROM book ORDER BY DUEDATE;

SELECT * FROM book WHERE id IN (SELECT DISTINCT BOOKID FROM library WHERE id = 101)

SELECT * FROM book WHERE id IN (SELECT DISTINCT BOOKID FROM library WHERE location = 'pune');

