CREATE TABLE CUST
	(
	CUSTID INT NOT NULL PRIMARY KEY,
	NAME VARCHAR(10) NOT NULL,
	BALANCE FLOAT NOT NULL
	)  ;

CREATE TABLE MERCHANT
	(
	MERCHID INT NOT NULL PRIMARY KEY,
	NAME VARCHAR(10) NOT NULL,
	BALANCE FLOAT NOT NULL
	)  ;

INSERT INTO CUST VALUES
(1,'NAMRATA',5000),
(2,'TEJASHREE',5000),
(3,'PAWAN',5000);

INSERT INTO Merchant VALUES
(101,'DMART',10000),
(102,'FLIPKART',5000),
(103,'AMAZON',5000);

UPDATE Merchant SET Balance = Balance+500 WHERE MerchId=104;

UPDATE CUST SET Balance = Balance-500 WHERE CUSTID=104;

select * from Cust;
select * from Merchant;