CREATE TABLE DEPT (
 DEPTNO              INTEGER NOT NULL,
 DNAME               VARCHAR(14),
 LOC                 VARCHAR(13),
 CONSTRAINT DEPT_PRIMARY_KEY PRIMARY KEY (DEPTNO));

INSERT INTO DEPT VALUES (10,'ACCOUNTING','NEW YORK');
INSERT INTO DEPT VALUES (20,'RESEARCH','DALLAS');
INSERT INTO DEPT VALUES (30,'SALES','CHICAGO');
INSERT INTO DEPT VALUES (40,'OPERATIONS','BOSTON');

CREATE TABLE EMP (
 EMPNO               INTEGER NOT NULL,
 ENAME               VARCHAR(10),
 JOB                 VARCHAR(9),
 MGR                 INTEGER CONSTRAINT EMP_SELF_KEY REFERENCES EMP (EMPNO),
 HIREDATE            DATETIME,
 SAL                 MONEY,
 COMM                MONEY,
 DEPTNO              INTEGER NOT NULL,
 CONSTRAINT EMP_FOREIGN_KEY FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO),
 CONSTRAINT EMP_PRIMARY_KEY PRIMARY KEY (EMPNO));

INSERT INTO EMP VALUES (7839,'KING','PRESIDENT',NULL,'17-NOV-81',5000,NULL,10);
INSERT INTO EMP VALUES (7698,'BLAKE','MANAGER',7839,'1-MAY-81',2850,NULL,30);
INSERT INTO EMP VALUES (7782,'CLARK','MANAGER',7839,'9-JUN-81',2450,NULL,10);
INSERT INTO EMP VALUES (7566,'JONES','MANAGER',7839,'2-APR-81',2975,NULL,20);
INSERT INTO EMP VALUES (7654,'MARTIN','SALESMAN',7698,'28-SEP-81',1250,1400,30);
INSERT INTO EMP VALUES (7499,'ALLEN','SALESMAN',7698,'20-FEB-81',1600,300,30);
INSERT INTO EMP VALUES (7844,'TURNER','SALESMAN',7698,'8-SEP-81',1500,0,30);
INSERT INTO EMP VALUES (7900,'JAMES','CLERK',7698,'3-DEC-81',950,NULL,30);
INSERT INTO EMP VALUES (7521,'WARD','SALESMAN',7698,'22-FEB-81',1250,500,30);
INSERT INTO EMP VALUES (7902,'FORD','ANALYST',7566,'3-DEC-81',3000,NULL,20);
INSERT INTO EMP VALUES (7369,'SMITH','CLERK',7902,'17-DEC-80',800,NULL,20);
INSERT INTO EMP VALUES (7788,'SCOTT','ANALYST',7566,'09-DEC-82',3000,NULL,20);
INSERT INTO EMP VALUES (7876,'ADAMS','CLERK',7788,'12-JAN-83',1100,NULL,20);
INSERT INTO EMP VALUES (7934,'MILLER','CLERK',7782,'23-JAN-82',1300,NULL,10);

--DISPLAY ALL EMPLOYEES IN ASCENDING ORDER OF NAME
SELECT * FROM EMP ORDER BY ENAME;

--DISLAY ALL EMPLOYEES IN DPET 10
SELECT * FROM EMP WHERE DEPTNO=10;

--DISPLAY ALL EMPLOYEES IN DEPT 10,20
SELECT * FROM EMP WHERE DEPTNO IN (10,20);

--DISPLAY ALL EMPS WHO ARE CLERKS
SELECT * FROM EMP WHERE JOB='CLERK';



--DISPLAY ALL EMPLOYEES WHOSE COMMISION IS NULL
SELECT * FROM EMP WHERE COMM IS NULL;

--DISPLAY ALL EMPLOYEES WHOSE SALARY BETWEEN 2000 AND 5000
SELECT * FROM EMP WHERE SAL BETWEEN 2000 AND 5000;

--DISPLAY ALL EMPLOYEES ANNUAL SALARY
SELECT ENAME, SAL*12 AS "ANNUAL SALARY" FROM EMP ;

--DISPLAY THE TOP 3 SALARY EARNING EMPLOYEES
SELECT * FROM EMP WHERE SAL IN (SELECT DISTINCT TOP 3  SAL FROM EMP ORDER BY SAL DESC);

SELECT * FROM EMP WHERE SAL IN (SELECT TOP 3  SAL FROM EMP ORDER BY SAL DESC);

--DISPLAY THE EMP JOINING DATE AND THE TENURE FROM JOINING
SELECT ENAME, HIREDATE, DATEDIFF(YEAR , HIREDATE , (SELECT GETDATE())) "TENURE IN YEAR" FROM EMP;


--DISPLAY ALL DEPTNOS FROM EMPLOYEE TABLE AVOIDING DUPLICATES
SELECT DISTINCT DEPTNO FROM EMP;

--DISPLAY THE DEPTNO OF SCOTT
SELECT  DEPTNO FROM EMP WHERE ENAME = 'SCOTT' ;

--DISPLAYY ALL EMPLOYEES WORKING IN DEPT OF SCOTT
SELECT * FROM EMP WHERE DEPTNO = (SELECT  DEPTNO FROM EMP WHERE ENAME = 'SCOTT') ;

--DISPLAY ALL EMPLOYEES WHO HAVE SAME JOB DESIGNATION AS "SMITH"
SELECT * FROM EMP WHERE JOB = (SELECT  JOB FROM EMP WHERE ENAME = 'SMITH') ;


--DISPLAY NO OF EMPLOYEES
SELECT COUNT(EMPNO) FROM EMP;

--DISPLAY SUM OF SALARIES OF EMPLOYEEESS
SELECT SUM(SAL) FROM EMP;

--DISPLAY AVG OF SALREIS OF EMPLOYEEES
SELECT AVG(SAL) FROM EMP;

--DISPLAY SUM,AVG,COUNT OF EMPLOYEES
SELECT 
COUNT(EMPNO) AS "NO OF EMPLOYEES", 
SUM(SAL) AS "SUM OF SALARIES", 
AVG(SAL) AS "AVERAGE SALAIES"
FROM EMP;

--DISPLAY THE DEPTWISE , HEADCOUNT
SELECT DEPTNO, COUNT(*) AS COUNT FROM EMP GROUP BY DEPTNO;

--DISPLAY THE JOBWIE HEADOCUNT
SELECT JOB, COUNT(*) AS COUNT FROM EMP GROUP BY JOB;


--DISPLAY DEPTWISE ,JOBWISE HEAD COUNT
SELECT DEPTNO, JOB, COUNT(*) AS "COUNT OF JOB" FROM EMP GROUP BY DEPTNO,JOB;

--DISPLAY THE DEPTWISE EMPLOYEES WHOSE COUNT GREATER THAN 2 AND WHO ARE IN DEPT 10 ,20.SORTY THE RESULT BY DESCENDING ORDER OF COUNT
SELECT EMPNO, ENAME,DEPTNO 
FROM EMP
WHERE DEPTNO IN (10,20)
AND DEPTNO IN (SELECT DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(DEPTNO)>2)
ORDER BY DEPTNO DESC;

--DISPLAY ENAME,DEPTNAME
SELECT E.ENAME AS "EMPLOYEE NAME", D.DNAME AS "DEPARTMENT NAME"
FROM EMP E JOIN  DEPT D
ON E.DEPTNO = D.DEPTNO;

--DISPLAY THE DEPTNAME WISE COUNT
SELECT D.DNAME, COUNT(E.EMPNO) 
FROM EMP E RIGHT JOIN  DEPT D
ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME;

--DISPLAY THE DEPTNAME,JOBWISE COUNT
SELECT D.DNAME, E.JOB, COUNT(E.EMPNO) 
FROM EMP E RIGHT JOIN  DEPT D
ON E.DEPTNO = D.DEPTNO
GROUP BY D.DNAME,E.JOB;



--DISPLAY ALL THE DEPTMENTS , WITH EMPLOYEES IF ANY (IF NO EMPS THEN DISPLAY NULL)
SELECT D.DEPTNO,D.DNAME,E.EMPNO, E.ENAME
FROM DEPT D LEFT JOIN EMP E 
ON D.DEPTNO= E.DEPTNO;

--DISPLAY THE DEPTMENTS WHERE THERE ARE NO EMPLOYEES
SELECT D.DEPTNO,D.DNAME
FROM DEPT D LEFT JOIN EMP E 
ON D.DEPTNO= E.DEPTNO
WHERE E.EMPNO IS NULL ;

--DISPLAY THE EMPNAME AND THEIR BOSSNAMES
SELECT E1.ENAME AS "EMPLOYEE NAME", E2.ENAME AS "MANAGER NAME"
FROM EMP E1 JOIN EMP E2 
ON E1.MGR= E2.EMPNO;

--DISPLAY ALL THE EMPNAMES AND BOSS NAMES IF ANY (IF NO BOSS DISPLAY NULL)
SELECT E1.ENAME AS "EMPLOYEE NAME", E2.ENAME AS "MANAGER NAME"
FROM EMP E1 LEFT JOIN EMP E2
ON E1.MGR= E2.EMPNO;

--DISPLAY ENMAE,DEPTNAME AND BOSSNAME .
SELECT E1.ENAME AS "EMPLOYEE NAME", D.DNAME AS "DEPARTMENT", E2.ENAME AS "MANAGER NAME"
FROM EMP E1 LEFT JOIN EMP E2 
ON E1.MGR= E2.EMPNO LEFT JOIN DEPT D
ON E1.DEPTNO=D.DEPTNO;

